
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/Users/mandel/Applications/CLion.app/Contents/bin/cmake/mac/x64/share/cmake-3.28/Modules/CMakeDetermineSystem.cmake:233 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Darwin - 22.6.0 - x86_64
...

---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/Users/mandel/Applications/CLion.app/Contents/bin/cmake/mac/x64/share/cmake-3.29/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Darwin - 22.6.0 - x86_64
...
